[package]
name = "music-mesa-tables-py"
version = "0.2.2"
edition = "2021"

[lib]
name = "music_mesa_tables"
crate-type = ["cdylib"]

[dependencies]
music_mesa_tables = { path = "..", version = "0.2.0" }
numpy = "0.23.0"
pyo3 = { version = "0.23.2", features = ["extension-module", "abi3-py310"] }
