[build-system]
requires = ["maturin>=1.2,<2.0"]
build-backend = "maturin"

[project]
name = "music-mesa-tables"
requires-python = ">=3.7"
dependencies = [
    "numpy>=1.21",
]

[tool.maturin]
profile = "release"
compatibility = "manylinux2014"
strip = true
